### ISSUE TITLE
feature request - OmniFocus Task Urls in pushed to other platforms in task details

### ISSUE THREAD

**Issue by johntrandall** [viamin/task_bridge#103]
Omnifocus tasks have urls, i.e., `omnifocus:///task/ebaqdWYKAOQ`. I can get these urls by right-clicking from a task or a project. I believe these URLs are also accessible via Applescript.

Once a task is pushed into Google Tasks (or elsewhere), I'd like to be able to get back to OmniFocus quickly for a more complete context.  A cheap way to do this might be to just append the OmniFocus URL for the task to the start or end of the notes/details on other platforms. 

This would also provide value when two-way sync is impossible or not-yet implemented. i.e., Rather than checking things off in Google Tasks or Reclaim, I could like back to OmniFocus and check off there once complete.

**Comment by viamin** [comment]
This is very similar to https://github.com/viamin/task_bridge/issues/91 - I think ensuring the `sync_id` is a URL might address this.

**Comment by johntrandall** [comment]
interesting. I'm not sure about the sync_id.

I'm advocating for exposing the URL to users– As a user, when I'm looking at my google task on my browser (or on Reclaim.ai), I can click a link which will show me the linked task in OmniFocus on my local machine.

**Comment by viamin** [comment]
I've just merged in #91 which also includes adding a URL (depending on the service.) If this doesn't cover what you were asking for in this issue, please let me know, otherwise feel free to close this.

**Comment by viamin** [comment]
Closing since this should be fixed in #91
